[package]
name = "test_fixtures"
version = "0.0.1"
authors = ["Alexander Koval <kovalidis@gmail.com>"]
edition = "2018"

[dependencies]
tantivy = { git = "https://github.com/tantivy-search/tantivy", rev = "14735ce" }
