[package]
name = "test_fixtures"
version = "0.0.1"
authors = ["Alexander Koval <kovalidis@gmail.com>"]
edition = "2018"

[dependencies]
# tantivy = "0.11.3"
tantivy = { git = "https://github.com/anti-social/tantivy", rev = "eba30d47" }
